name: keep-streamlit-awake

on:
  schedule:
    # A cada 8 horas
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit
        run: |
          curl \
            -A "Mozilla/5.0" \
            --max-redirs 5 \
            -sS \
            -o /dev/null \
            -w "HTTP %{http_code}\n" \
            "https://gustavo-curriculo.streamlit.app/" || true